version: '3'
services:
      web:
              image: flask_ishi_v1
              build: .
              ports:
                      - "8006:8080"
              volumes:
                      - persistent_volume:/app/volumes
volumes:
  type: mapping
persistent_volume:
  driver: local
  driver_opts:
    o: bind
    type: none
    device: /home/ubuntu/Flask-Portfoilo/volumes
    
    # replace just flask_portfolio